name: Build and Deploy

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build-and-deploy:
    runs-on: [ "self-hosted" ]
    steps:
      - name: Build and start containers
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            cd /home/emargement/PolyPresence
          else
            cd /home/emargement/PolyPresence_preprod
          fi
          git fetch origin
          git reset --hard origin/${{ github.ref_name }}
          docker compose build
          docker compose up -d
